version: '3'
services:
  server:
    build: ./server
    container_name: test-case-server
    ports:
      - 8080:8080

  client:
    build: ./client
    container_name: test-case-client
    depends_on:
      - server
